/* build-css.mjs — concatenates all site CSS into css/bundle.css in cascade order.
 * Source files in css/ remain the editable truth; re-run after any CSS edit:
 *   node build-css.mjs
 */
import fs from 'fs';

const ORDER = [
  // base layer
  'css/base/fonts.css',
  'css/base/tokens.css',
  'css/base/reset.css',
  'css/base/typography.css',
  // components
  'css/components/navbar.css',
  'css/components/buttons.css',
  'css/components/cards.css',
  'css/components/footer.css',
  'css/components/consent.css',
  // layout
  'css/bento.css',
  // pages (namespaced by page-specific classes; order between them is inert)
  'css/pages/home.css',
  'css/pages/blog.css',
  'css/pages/scores.css',
  'css/pages/category.css',
  'css/pages/memory.css',
  'css/pages/reaction.css',
  'css/pages/reading.css',
  'css/pages/focus.css',
  'css/pages/spatial.css',
  'css/pages/verbal.css',
  'css/pages/creativity.css',
  'css/pages/career.css',
  'css/pages/productivity.css',
  'css/pages/studyplanner.css',
  'css/pages/processingspeed.css',
  'css/pages/about.css',
  'css/pages/error.css',
  'css/pages/test.css',
  'css/pages/intake.css',
  'css/pages/results.css',
];

let out = '';
for (const f of ORDER) {
  if (!fs.existsSync(f)) { console.error('MISSING', f); process.exit(1); }
  let s = fs.readFileSync(f, 'utf8');
  // strip comments (safe: none of our CSS uses "*/" inside content strings)
  s = s.replace(/\/\*[\s\S]*?\*\//g, '');
  out += s + '\n';
}

/* Conservative, string-aware minifier.
 * Inside quoted strings nothing is touched. Outside strings:
 *   - all whitespace runs collapse to a single space
 *   - spaces adjacent to { } ; , are removed
 *   - ";}" becomes "}"
 * Deliberately NOT touched: spaces around ":" (descendant+pseudo selectors)
 * and around + - > ~ (calc() and combinator safety). */
function minify(css) {
  let res = '';
  let i = 0, quote = null;
  while (i < css.length) {
    const ch = css[i];
    if (quote) {
      res += ch;
      if (ch === quote && css[i - 1] !== '\\') quote = null;
      i++; continue;
    }
    if (ch === '"' || ch === "'") { quote = ch; res += ch; i++; continue; }
    if (/\s/.test(ch)) {
      while (i < css.length && /\s/.test(css[i])) i++;
      const prev = res[res.length - 1];
      const next = css[i];
      if (!prev || !next) continue;
      if ('{};,'.includes(prev) || '{};,'.includes(next)) continue;
      res += ' ';
      continue;
    }
    res += ch; i++;
  }
  return res
    .replace(/;}/g, '}')
    /* Proven safe for this codebase (audited: no "sel :pseudo" patterns,
       no > or ~ inside calc). "+" is deliberately left alone for calc(). */
    .replace(/: /g, ':')
    .replace(/ ?> ?/g, '>')
    .replace(/ ?~ ?/g, '~');
}

const raw = out;
out = '/* AurorIQ bundled stylesheet — generated by build-css.mjs. Do not edit; edit css/ sources and rebuild. */\n' + minify(out);
fs.writeFileSync('css/bundle.css', out);

// sanity: brace balance + balance must match the unminified input
const bal = (s) => (s.match(/{/g) || []).length - (s.match(/}/g) || []).length;
const open = (out.match(/{/g) || []).length;
const close = (out.match(/}/g) || []).length;
if (open !== close || bal(raw) !== 0) { console.error(`BRACE MISMATCH ${open} vs ${close}`); process.exit(1); }
console.log(`bundle.css written: ${(raw.length/1024).toFixed(1)} KB raw -> ${(out.length/1024).toFixed(1)} KB minified (${(100-100*out.length/raw.length).toFixed(1)}% smaller), braces ${open}=${close}`);
